import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Container, Theme } from "@radix-ui/themes";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Navbar";
import ProgressBarProvider from "@/components/ProgressBarProvider";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ProgressBarProvider>
          <Theme>
            <Navbar token={token} />

            <Container size={"4"}>{children}</Container>

            <ToastContainer position="bottom-right" />
          </Theme>
        </ProgressBarProvider>
      </body>
    </html>
  );
}
